
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_SUB = 5;
  public static final int TK_DIV = 7;
  public static final int TK_INPUT = 12;
  public static final int TK_ADD = 4;
  public static final int TK_L_P = 8;
  public static final int TK_SEP = 2;
  public static final int TK_LET = 10;
  public static final int TK_ELSE = 15;
  public static final int TK_WHILE = 19;
  public static final int TK_THEN = 14;
  public static final int TK_EQU = 11;
  public static final int TK_VAR = 25;
  public static final int TK_L_C = 20;
  public static final int EOF = 0;
  public static final int TK_L_B = 16;
  public static final int TK_R_P = 9;
  public static final int TK_MOD = 18;
  public static final int TK_COMMA = 22;
  public static final int error = 1;
  public static final int TK_ICNST = 24;
  public static final int TK_FUNC = 23;
  public static final int TK_MULT = 6;
  public static final int TK_R_C = 21;
  public static final int TK_R_B = 17;
  public static final int TK_PRINT = 3;
  public static final int TK_IF = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_SEP",
  "TK_PRINT",
  "TK_ADD",
  "TK_SUB",
  "TK_MULT",
  "TK_DIV",
  "TK_L_P",
  "TK_R_P",
  "TK_LET",
  "TK_EQU",
  "TK_INPUT",
  "TK_IF",
  "TK_THEN",
  "TK_ELSE",
  "TK_L_B",
  "TK_R_B",
  "TK_MOD",
  "TK_WHILE",
  "TK_L_C",
  "TK_R_C",
  "TK_COMMA",
  "TK_FUNC",
  "TK_ICNST",
  "TK_VAR"
  };
}

